{"timestamp":"2025-05-18T16:10:26.068756","level":"info","event":"DAG bundles loaded: dags-folder, example_dags","logger":"airflow.dag_processing.bundles.manager.DagBundlesManager"}
{"timestamp":"2025-05-18T16:10:26.069686","level":"info","event":"Filling up the DagBag from /opt/airflow/dags/load_csv_to_postgres.py","logger":"airflow.models.dagbag.DagBag"}
{"timestamp":"2025-05-18T16:10:26.136573Z","level":"info","event":"Task instance is in running state","chan":"stdout","logger":"task"}
{"timestamp":"2025-05-18T16:10:26.137237Z","level":"info","event":" Previous state of the Task instance: TaskInstanceState.QUEUED","chan":"stdout","logger":"task"}
{"timestamp":"2025-05-18T16:10:26.137939Z","level":"info","event":"Current task name:load_csv","chan":"stdout","logger":"task"}
{"timestamp":"2025-05-18T16:10:26.138235Z","level":"info","event":"Dag name:load_csv_to_postgres","chan":"stdout","logger":"task"}
{"timestamp":"2025-05-18T16:10:26.142964","level":"error","event":"Task failed with exception","logger":"task","error_detail":[{"exc_type":"UndefinedTable","exc_value":"relation \"users\" does not exist\nLINE 2:                         INSERT INTO users (id, name, email, ...\n                                            ^\n","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":838,"name":"run"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":1130,"name":"_execute_task"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/bases/operator.py","lineno":408,"name":"wrapper"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/operators/python.py","lineno":212,"name":"execute"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/operators/python.py","lineno":235,"name":"execute_callable"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/callback_runner.py","lineno":81,"name":"run"},{"filename":"/opt/airflow/dags/load_csv_to_postgres.py","lineno":32,"name":"load_csv_to_postgres"}]}]}
{"timestamp":"2025-05-18T16:10:26.144712Z","level":"info","event":"Task instance in failure state","chan":"stdout","logger":"task"}
{"timestamp":"2025-05-18T16:10:26.145239Z","level":"info","event":"Task start","chan":"stdout","logger":"task"}
{"timestamp":"2025-05-18T16:10:26.145613Z","level":"info","event":"Task:<Task(PythonOperator): load_csv>","chan":"stdout","logger":"task"}
{"timestamp":"2025-05-18T16:10:26.145954Z","level":"info","event":"Failure caused by relation \"users\" does not exist","chan":"stdout","logger":"task"}
{"timestamp":"2025-05-18T16:10:26.146222Z","level":"info","event":"LINE 2:                         INSERT INTO users (id, name, email, ...","chan":"stdout","logger":"task"}
{"timestamp":"2025-05-18T16:10:26.146486Z","level":"info","event":"                                            ^","chan":"stdout","logger":"task"}
{"timestamp":"2025-05-18T16:10:26.146793Z","level":"info","event":"","chan":"stdout","logger":"task"}
